streaming_music:
  outputs:
    dev:
      dataset: streamify_stg
      fixed_retries: 1
      keyfile: C:\Users\pbang\AppData\Roaming\gcloud\application_default_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: streamify_prod
      fixed_retries: 1
      keyfile: C:\Users\pbang\AppData\Roaming\gcloud\application_default_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev